# Site settings

title: "Dirk's Resume"
description: "A resume for Dirk's and GitHub Pages sites."


# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed

# Resume settings
resume_avatar:                  "true"

resume_name:                    "Dirk Jansen van Rensburg"
resume_title:                   "Full Stack Web Developer"
resume_contact_email:           "dirkvanrensburg5@gmail.com"
resume_contact_telephone:       "(+27) 082-546-1005 "
resume_contact_address:         "Johannesburg, SA"
resume_header_contact_info: "Johannesburg, SA |(+27) 082-546-1005 | dirkvanrensburg5@gmail.com"
resume_header_intro: "<p>Hi, I’m Dirk Jansen van Rensburg. I’m a Full Stack Web Developer. I have been doing Web development since Sep 2017 and created a web design company Focus Web Design to do web development part time. I push myself t learn new skills every day by doing
        courses in the field. My full-time job is to develop and maintain a hospital system for Arwyp Medical Centre using BASIC programming language for the past 8 years. My passion for web development came when we started integrating with dynamic programming
        into web development for the hospital system where I have created multiple sites for the Hospital link to a web server.</p>"


# use "yes" to display the email contact button,
# "no" to display an "I'm not looking for work" message,
# or remove the resume_looking_for_work option entirely
# to leave blank
resume_looking_for_work:        "yes"

# Decide which sections to use
# comment out to hide
resume_section_experience:      true
resume_section_education:       true
resume_section_skills:          true
# resume_section_recognition:     true
#resume_section_links:           true
#resume_section_associations:    true
resume_section_interests:       true
resume_section_projects:        true

# Resume social links
# uncomment the options you wish to display, and add your own URL
resume_social_links:
  resume_github_url:            "https://github.com/dirk005"
  # resume_twitter_url:           "http://twitter.com/jglovier"
  # resume_dribbble_url:          "https://dribbble.com/jag"
  # resume_facebook_url:          "insert Facebook URL here"
  resume_linkedin_url:          "https://www.linkedin.com/in/dirk-jansen-van-rensburg-597547120/"
  # resume_instagram_url:         "insert your Instagram URL here"
  resume_website_url:           "https://dirk005.github.io/Portfolio/"
resume_print_social_links:      true

# Design settings
resume_theme:                   default

# Note: when editing locally, remember to restart
# your Jekyll server when you edit this file. Changes
# to _config.yml are only recognized when the server starts
